all: material.o liquid.o hard.o construction.o distributor.o truck.o

material.o: Material.h Material.cpp
	g++ -c Material.cpp

liquid.o: LiquidMaterial.h LiquidMaterial.cpp
	g++ -c LiquidMaterial.cpp

hard.o: HardMaterial.h HardMaterial.cpp
	g++ -c HardMaterial.cpp

construction.o: Construction.h Construction.cpp
	g++ -c Construction.cpp

distributor.o: Distributor.h Distributor.cpp
	g++ -c Distributor.cpp

truck.o: Truck.h Truck.cpp
	g++ -c Truck.cpp